# Generated by Django 3.0.8 on 2020-07-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('img_1', models.ImageField(upload_to='slideimage')),
                ('img_2', models.ImageField(upload_to='slideimage')),
                ('img_3', models.ImageField(upload_to='slideimage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('product_img1', models.ImageField(upload_to='product_image')),
                ('product_img2', models.ImageField(blank=True, upload_to='product_image')),
                ('product_img3', models.ImageField(blank=True, upload_to='product_image')),
                ('product_img4', models.ImageField(blank=True, upload_to='product_image')),
                ('product_img5', models.ImageField(blank=True, upload_to='product_image')),
                ('product_price', models.IntegerField()),
                ('address', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('contact_no', models.CharField(default='', max_length=15)),
                ('product_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
            ],
        ),
    ]
